/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/github.glb -t -T -o src\components\3DModels\GitHubLogo.tsx 
Files: public/models/github.glb [253.39KB] > C:\Users\Gabri\Desktop\Projects\portfolioV2\src\components\3DModels\github-transformed.glb [8.96KB] (96%)
Author: sudo-self (https://sketchfab.com/sudo-self)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/github-b2bd1d8290e44ce49e7e41dd495592b5
Title: GitHub
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.Mesh;
  };
  materials: {
    material_0: THREE.MeshPhysicalMaterial;
  };
};

const GitHubLogo = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(
    "/models/github.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.material_0}
        position={[-42.721, 48.765, 27.99]}
        rotation={[0, Math.PI / 4, -Math.PI]}
        scale={[-4.167, 4.167, 4.167]}
      />
    </group>
  );
};

useGLTF.preload("/models/github.glb");

export default GitHubLogo;
