/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/python_logo.glb -t -T -o src\components\3DModels\PythonLogo.tsx 
Files: public/models/python_logo.glb [323.49KB] > C:\Users\Gabri\Desktop\Projects\portfolioV2\src\components\3DModels\python_logo-transformed.glb [32.02KB] (90%)
Author: Alex human (https://sketchfab.com/alex-human)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/python-logo-f8e026fb248646b4be725defaa121d98
Title: Python Logo
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
  };
  materials: {
    blue: THREE.MeshStandardMaterial;
    yellow: THREE.MeshStandardMaterial;
  };
};

const PythonLogo = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(
    "/models/python_logo.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.blue}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.yellow}
        rotation={[0, 0, Math.PI]}
      />
    </group>
  );
};

useGLTF.preload("/models/python_logo.glb");

export default PythonLogo;
