/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ts-logo.glb -t -T -o src\components\3DModels\TypeScriptLogo.tsx 
Files: public/models/ts-logo.glb [358.67KB] > C:\Users\Gabri\Desktop\Projects\portfolioV2\src\components\3DModels\ts-logo-transformed.glb [24.44KB] (93%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { JSX } from "react";
import { Float } from "@react-three/drei";

type GLTFResult = GLTF & {
  nodes: {
    TypeScriptsvg001: THREE.Mesh;
    TypeScriptsvg001_1: THREE.Mesh;
  };
  materials: {
    blue: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
  };
};

const TypeScriptLogo = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(
    "/models/ts-logo.glb",
  ) as unknown as GLTFResult;
  return (
    <Float floatingRange={[-0.05, 0.05]} rotationIntensity={0.5}>
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes.TypeScriptsvg001.geometry}
          material={materials.blue}
        />
        <mesh
          geometry={nodes.TypeScriptsvg001_1.geometry}
          material={materials.white}
        />
      </group>
    </Float>
  );
};

useGLTF.preload("/models/ts-logo.glb");

export default TypeScriptLogo;
